# Generated by Django 3.2.8 on 2022-02-25 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre_songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_genre', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_song', models.CharField(max_length=100)),
                ('avtor', models.CharField(max_length=100)),
                ('feat', models.JSONField(blank=True, null=True)),
                ('song_path', models.FileField(upload_to='song/')),
                ('photo_song', models.ImageField(upload_to='song/photo')),
                ('album', models.CharField(blank=True, max_length=100, null=True)),
                ('share', models.CharField(default='HzjEqOFwecXAjlPNwtWbzkkepPuFmxSENggrUsaryUeiSletPs', max_length=50)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.genre_songs')),
            ],
        ),
    ]
