# Generated by Django 3.2.8 on 2022-03-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20220303_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='time',
            field=models.CharField(default=models.FileField(upload_to='song/'), max_length=10),
        ),
        migrations.AlterField(
            model_name='music',
            name='share',
            field=models.CharField(default='kqPycdRfWZyvkqONbJlcRzjXOgvkKpZrhRJvhdCwwTzxuJJWMp', max_length=50),
        ),
    ]
