# Generated by Django 3.1.4 on 2022-03-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20220303_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre_songs',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='music',
            name='share',
            field=models.CharField(default='QiTzpaEvKmcefNDdIEJXmgWSpHTuPvARemQqqySqCGQfpJvQGF', max_length=50),
        ),
        migrations.AlterField(
            model_name='music',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
