# Generated by Django 3.1.4 on 2022-03-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_auto_20220322_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='share',
            field=models.CharField(default='UXWzXPPWOnmlEwlDeTFGhSULttfxTsabKAGkelTwyYsxSVeHXE', max_length=50),
        ),
    ]
