# Generated by Django 3.1.4 on 2022-03-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_auto_20220322_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='share',
            field=models.CharField(default='cSzfqVVGnHVZZWiZdUtAYcXRQdQEbFafPcFFEcSVlrXCUuzeOj', max_length=50),
        ),
    ]
