# Generated by Django 3.1.4 on 2022-03-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_auto_20220324_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='share',
            field=models.CharField(default='PynWYhltTkaaungMjpiIbIahzIhZpvSsvIZRcTAtedDvlCwtSs', max_length=50),
        ),
    ]
