# Generated by Django 3.1.4 on 2022-03-29 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0024_playlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlists',
            name='share',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='playlists',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='playlist_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
