# Generated by Django 3.1.4 on 2022-03-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_auto_20220325_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='music',
            new_name='music_artist',
        ),
    ]
