# Generated by Django 3.2.11 on 2022-01-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('about_me', models.TextField(blank=True)),
                ('date_of_birth', models.DateTimeField(auto_now_add=True)),
                ('sex', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='photos_user/%Y/%m/%d/')),
                ('country', models.CharField(max_length=150)),
                ('followers', models.IntegerField()),
                ('sub', models.IntegerField()),
                ('music', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
