# Generated by Django 3.2.11 on 2022-01-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='followers',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='sub',
            field=models.IntegerField(blank=True),
        ),
    ]
