# Generated by Django 3.2.11 on 2022-01-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0003_auto_20220127_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='sub',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
