# Generated by Django 3.1.4 on 2022-03-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_auto_20220324_1050'),
        ('profile_user', '0007_profile_music_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='music_list',
        ),
        migrations.AddField(
            model_name='profile',
            name='music_list',
            field=models.ManyToManyField(blank=True, related_name='music', to='music.Music'),
        ),
    ]
