# Generated by Django 3.2.11 on 2022-02-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_article_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='share',
            field=models.CharField(default='jcovMKUEWpxmEEZsJsPreoYKudbkFhtFQbeTvJDRUNEhYKpLDo', max_length=50),
        ),
    ]
