# Generated by Django 3.2.11 on 2022-02-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_article_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='header',
        ),
        migrations.AlterField(
            model_name='article',
            name='share',
            field=models.CharField(default='szkXTAyiOoIvRvFVeWlsusVYjyMuMGmuVGmGAzBRfqgeFfNurS', max_length=50),
        ),
    ]
