# Generated by Django 3.2.11 on 2022-02-09 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazine', '0004_auto_20220208_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='share',
            field=models.CharField(default='ctCmekjzOQzqKGqyFtZzhZVPAgWWnJemTIbxRYzTliYRyxOaXq', max_length=50),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.JSONField()),
                ('post_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.article')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('post_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.article')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
