# Generated by Django 3.2.8 on 2022-02-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0005_auto_20220209_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='disslike',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='share',
            field=models.CharField(default='zCQKUJmKPiteNXgJYTnTGRWsINXnhgmxwrVgTcpmbIaXdpbSCY', max_length=50),
        ),
    ]
