# Generated by Django 3.2.8 on 2022-02-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0007_alter_article_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='share',
            field=models.CharField(default='GxCKCqtcKadeaTJsDfGcMzzxUEwrecjcqrRYDBXhJtYfVkpHoo', max_length=50),
        ),
    ]
