# Generated by Django 3.2.8 on 2022-03-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0010_auto_20220225_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='share',
            field=models.CharField(default='mvlGIfvmbimdFCGxGkeoDHfYvFgIaAIeethDyRyLvTihRPoRcW', max_length=50),
        ),
    ]
