# Generated by Django 3.1.4 on 2022-03-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0012_alter_article_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='share',
            field=models.CharField(default='gKMFYFTyJCgynpNpjrdgGUdKwLlAdMDPCmqzIfuNOrLBwhiDJA', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='genre_article',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
