# Generated by Django 3.1.4 on 2022-03-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0023_auto_20220308_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='share',
            field=models.CharField(default='yXcIQVWTjAKvNKuLyJCXvddcOSPxIDvcIRbhnTcvmPFoJmnLzC', max_length=50),
        ),
    ]
