# Generated by Django 3.1.4 on 2022-03-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0025_auto_20220308_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='share',
            field=models.CharField(default='zNaCCpthgVcQxYodtftlFoNphXsjAiuGEYdHWjkDHqqLVIKmRM', max_length=50),
        ),
    ]
